---
- hosts: all
  pre_tasks:
    - name: "Installing which"
      action: yum
              name={{ item }}
              state=installed
      with_items:
        - net-tools
        - which
        - libselinux-python
    - name: "Make sure we can sudo in the deployment"
      lineinfile: dest=/etc/sudoers line="Defaults    !requiretty" state=present
    - name: "Make sure the docs are installed to"
      lineinfile: dest=/etc/yum.conf line="tsflags=nodocs" state=absent

  roles:
    - role: galaxyprojectdotorg.postgresql
      when: inventory_hostname in groups['postgresql']
    - role: geerlingguy.mysql
      when: inventory_hostname in groups['mysql']
    - role: ansible-zabbix-server
