---
# tasks file for wdijkerman.zabbix

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Get Apache version"
  action: shell apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
  changed_when: False
  register: apachectl_version

- name: "Set correct apache_version"
  set_fact:
    apache_version: "{{ apachectl_version.stdout }}"

- name: "Install the correct repository"
  include: "Debian.yml"
  tags:
    - always

- name: "Installing the mysql database"
  include: "mysql.yml"
  tags:
    - always

- name: "Configure zabbix-server"
  template: src=zabbix_server.conf.j2
            dest=/etc/zabbix/zabbix_server.conf
            owner=zabbix
            group=zabbix
            mode=0644
  notify: zabbix-server restarted

- name: "Create include dir zabbix-server"
  file: path={{ server_include }}
        owner=zabbix
        group=zabbix
        state=directory
        mode=0644

- name: "Create zabbix-web directory"
  file: path=/etc/zabbix/web
        owner={{ apache_user }}
        group={{ apache_group }}
        state=directory
        mode=0755
  when: zabbix_web

- name: "Configure zabbix-web"
  template: src=zabbix.conf.php.j2
            dest=/etc/zabbix/web/zabbix.conf.php
            owner={{ apache_user }}
            group={{ apache_group }}
            mode=0644
  when: zabbix_web

- name: "Make sure Zabbix Server is running"
  service: name=zabbix-server state=started enabled=yes use=service
